queue_rules:
  - name: dependency-update
    conditions:
      - check-success=Build and Test (ubuntu-latest, 3.3.3, temurin@11)
      - check-success=Build and Test (ubuntu-latest, 2.13.14, temurin@11)      
      - check-success=Build and Test (ubuntu-latest, 2.12.19, temurin@11)

pull_request_rules:
  - name: Merge using the merge queue
    conditions:
      - base=main
      - check-success=Build and Test (ubuntu-latest, 3.3.3, temurin@11)      
      - check-success=Build and Test (ubuntu-latest, 2.13.14, temurin@11)      
      - check-success=Build and Test (ubuntu-latest, 2.12.19, temurin@11)
      - author=scala-steward
    actions:
      queue:
        name: dependency-update
